In [11]:
import numpy as np
import math

Dot product illustration

In [5]:
a = [2,3,4,5]
b = [5,6,7,8]

np.dot(a,b)

96

Dot product - application

Similarity between emails

frequency of the words; apply dot product

In [7]:
m1 = [2,1,0,0]
m2 = [0,0,1,1]
m3 = [1,1,0,0]
m4 = [1,1,1,0]

In [22]:
dot1_2 = np.dot(m1,m2)

print(dot1_2)

m1_mag = np.linalg.norm(np.array(m1))
m2_mag = np.linalg.norm(np.array(m2))

print(m1_mag, m2_mag)

theta = np.arccos(dot1_2/(m1_mag*m2_mag)) * (180.0/math.pi)

print(theta)

0
2.23606797749979 1.4142135623730951
90.0


In [23]:
dot1_3 = np.dot(m1,m3)

print(dot1_3)

m1_mag = np.linalg.norm(np.array(m1))
m3_mag = np.linalg.norm(np.array(m3))

print(m1_mag, m3_mag)

theta = (np.arccos(dot1_3/(m1_mag*m3_mag))) * (180.0/math.pi)
print(theta)


3
2.23606797749979 1.4142135623730951
18.434948822922017


In [24]:
dot1_4 = np.dot(m1,m4)

print(dot1_4)

m1_mag = np.linalg.norm(np.array(m1))
m4_mag = np.linalg.norm(np.array(m4))

print(m1_mag, m4_mag)

theta = (np.arccos(dot1_4/(m1_mag*m4_mag))) * (180.0/math.pi)
print(theta)

3
2.23606797749979 1.7320508075688772
39.231520483592256


In [25]:
dot2_3 = np.dot(m2,m3)

print(dot2_3)

m2_mag = np.linalg.norm(np.array(m2))
m3_mag = np.linalg.norm(np.array(m3))

print(m2_mag, m3_mag)

theta = (np.arccos(dot2_3/(m2_mag*m3_mag))) * (180.0/math.pi)
print(theta)


0
1.4142135623730951 1.4142135623730951
90.0


In [26]:
dot2_4 = np.dot(m2,m4)

print(dot2_4)

m2_mag = np.linalg.norm(np.array(m2))
m4_mag = np.linalg.norm(np.array(m4))

print(m2_mag, m4_mag)

theta = (np.arccos(dot2_4/(m2_mag*m4_mag))) * (180.0/math.pi)
print(theta)


1
1.4142135623730951 1.7320508075688772
65.90515744788931


In [27]:
dot3_4 = np.dot(m3,m4)

print(dot3_4)

m3_mag = np.linalg.norm(np.array(m3))
m4_mag = np.linalg.norm(np.array(m4))

print(m3_mag, m4_mag)

theta = (np.arccos(dot3_4/(m3_mag*m4_mag))) * (180.0/math.pi)
print(theta)


2
1.4142135623730951 1.7320508075688772
35.26438968275466


In [28]:
dot1_4 = np.dot(m1,m4)

print(dot1_4)

m1_mag = np.linalg.norm(np.array(m1))
m4_mag = np.linalg.norm(np.array(m4))

print(m1_mag, m4_mag)

theta = (np.arccos(dot1_4/(m1_mag*m4_mag))) * (180.0/math.pi)
print(theta)

3
2.23606797749979 1.7320508075688772
39.231520483592256


Check points if colinear

How to find if three points are collinear?:

There are two methods to find if three points are collinear.
#One is slope formula method and the other is area of triangle method.
#Slope formula method to find that points are collinear.
#Three or more points are collinear, if slope of any two pairs of points is same.
#With three points A, B and C, three pairs of points can be formed, they are: AB, BC and AC.
#If Slope of AB = slope of BC = slope of AC, then A, B and C are collinear points.

In [29]:
# Slope based solution to check if three 
# points are collinear. 

# function to check if 
# point collinear or not 
def collinear(x1, y1, x2, y2, x3, y3): 
	
	if ((y3 - y2)*(x2 - x1) == (y2 - y1)*(x3 - x2)): 
		print ("Yes") 
	else: 
		print ("No") 

# Driver Code 
x1, x2, x3, y1, y2, y3 = 1, 1, 0, 1, 6, 9
collinear(x1, y1, x2, y2, x3, y3); 

# This code is contributed 
# by Sachin Bisht 


No


In [32]:
# Python program to check 
# if three points are collinear 
# or not using area of triangle. 

# function to check if 
# point collinear or not 
def collinear(x1, y1, x2, y2, x3, y3): 
	
	""" Calculation the area of 
		triangle. We have skipped 
		multiplication with 0.5 to 
		avoid floating point computations """
	a = x1 * (y2 - y3) + x2 * (y3 - y1) + x3 * (y1 - y2) 

	if (a == 0): 
		print ("Yes")
	else: 
		print ('No')

# Driver Code 
x1, x2, x3, y1, y2, y3 = 1, 1, 1, 1, 4, 5
collinear(x1, y1, x2, y2, x3, y3) 

# This code is contributed 
# by Sachin Bisht 


Yes


Linearly Independent

In the theory of vector spaces, a set of vectors is said to be linearly dependent if at least one of the vectors in the set can be defined as a linear combination of the others; if no vector in the set can be written in this way, then the vectors are said to be linearly independent.

In [35]:
A = np.array([[2, 1, -1], 
              [1, 0, -1], 
              [-2, 0, 1]])

np.linalg.norm(A)

3.605551275463989

In [38]:
matrix = np.array(
    [
        [0, 1 ,0 ,0],
        [0, 0, 1, 0],
        [0, 1, 1, 0],
        [1, 0, 0, 1]
    ])

lambdas, V =  np.linalg.eig(matrix.T)
# The linearly dependent row vectors 
print (matrix[lambdas == 0,:])


print (np.linalg.det(matrix))

[[0 1 1 0]]
0.0


In [33]:
# inverse
A = np.array([[2, 1, -1], 
              [1, 0, -1], 
              [-2, 0, 1]])

np.linalg.inv(A)

array([[ 0., -1., -1.],
       [ 1.,  0.,  1.],
       [-0., -2., -1.]])

In [40]:
# system of three equations
A = np.array([[1, 5, -1], 
              [2, 3, -2], 
              [-3, 4, 0]])
b = np.array([1, 2, 0])

# compute the inverse
A_inv = np.linalg.inv(A)

# solution: A_inv * b
x = np.dot(A_inv, b)

print(x)

[ 0.  0. -1.]


System of Linear Equations
Solve the following system of three equations and three unknowns in Numpy and report the solution:

2x+6y−z=0

x+2y−2z=1

−5x+2z=8

In [41]:
# system of three equations
A = np.array([[2, 6, -1], 
              [1, 2, -2], 
              [-5, 0, 2]])
b = np.array([0, 1, 8])

# compute the inverse
A_inv = np.linalg.inv(A)

# solution: A_inv * b
x = np.dot(A_inv, b)

print(x)

[-2.   0.5 -1. ]


In [43]:
# system of two equations
A = np.array([[1, 2], 
              [3, 6]])
b = np.array([5, 10])

print(np.linalg.det(A))

# compute the inverse
A_inv = np.linalg.inv(A)

# solution: A_inv * b
x = np.dot(A_inv, b)
print(x)

-3.330669073875464e-16
[-3.00239975e+16  1.50119988e+16]


In [49]:
A = np.array([[1, 3], 
              [2, 6]])
print(A)

np.linalg.matrix_rank(A)

[[1 3]
 [2 6]]


1

In [51]:
A = np.array([[2, -1, -1], 
              [2, -1, 1], 
              [4, -2, -3]])

b = np.array([1, 0, -1])

print(np.linalg.det(A))

print(np.linalg.matrix_rank(A))

0.0
2


In [58]:
# A = np.array([[2,0],[0,5]])
A = np.array([[4,9],[7,6]])
# A = np.array([[-1, 0], 
#               [0, 1]])


print(A)

print(np.linalg.eigvals(A))
print(np.linalg.eig(A))

[[4 9]
 [7 6]]
[-3. 13.]
(array([-3., 13.]), array([[-0.78935222, -0.70710678],
       [ 0.61394061, -0.70710678]]))
