### Essential Topics of Linear Algebra

1. Linear combination
2. Basis Vectors
3. Linear Transformation
4. Eigenvectors and Eigendecomposition

In [1]:
import pandas as pd
import numpy as np

### Linear Combination

A linear combination of a set of vectors is an expression obtained by multiplying those set of vectors with a scalar/real number and then adding them up. For example,

If you have a set of vectors, say (2,3) and (3,4) a linear combination of these 2 vectors would be m(2,3) + n(3,4), where m and n are some real numbers. Since m and n can take any values, the number of linear combinations are infinite. The linear combination vector would therefore be shown as (2m + 3n , 3m+ 4n)

In [2]:
#Let's write a short code and understand this concept
v1 = np.array([2,3])
v2 = np.array([3,4])
m = 1
n = 2

lincom = m*v1 +  n*v2
lincom

array([ 8, 11])

We can do the reverse part as well. That is find the values of m,n for which the given vector is a linear combination of the previous two vectors

In [3]:
#Let's take an example to understand this concept.
#We'll be using the np.linalg.solve function from the numpy library

lincom2  = ([8,11])
setvec = np.array([[2,3],[3,4]])
m,n = np.linalg.solve(setvec, lincom2)
m,n

(0.9999999999999994, 2.0000000000000004)

Thus you've understood how linear combinations work.  Now the next interesting thing to ponder up would be to answer one important question - can every vector in 2-D space be represented as a linear combination of (2,3) and (3,4)? 

#### Or more generally can any vector in 2-D space be represented as a linear combination of any set of vectors?

In [4]:
#Let's investigate now by taking another set of vectors 
#We would be using (2,0) and (3,0)
lincom2  = ([6,3])
setvec = np.array([[2,3],[3,4]])
m,n = np.linalg.solve(setvec, lincom2)
round(m),round(n) 


(-15.0, 12.0)

The reason why these vectors - (2,0) and (3,0) would throw up an error is because they are collinear, i.e. one of the vectors can be represented as a scalar multiple of the other vector. 
#### (3,0) = 1.5(2,0).

Collinear vectors always have the same direction and can always be represented as a scalar multiple of one another. So, a linear combination of these collinear vectors would also have the same direction,i.e. again be collinear

m(3,0) + n(2,0) = (3m+2n,0)

Therefore, not all vectors can be represented as a linear combination of these collinear vectors since they might have a different direction from the previous ones.

### Basis Vectors

So if you actually have a set of vectors where no matter what other vector you pick, it can always be represented as a linear combination of that set, then it is known as the basis vectors for that data-space or dimension. For example the vectors (2,3) and (3,4) can represent any other vector in 2-D as a linear combination of themeselves and hence they're a set of basis vectors for the 2-D space.

In [5]:
#Verifying the basis vectors once again
lincom2  = ([6,3])
setvec = np.array([[2,3],[3,4]])
m,n = np.linalg.solve(setvec, lincom2)
round(m),round(n)

(-15.0, 12.0)

In [6]:
#This is also true for the standard basis vectors i(1,0) and j(0,1) that we use
lincom2  = ([6,3])
setvec = np.array([[1,0],[0,1]])
m,n = np.linalg.solve(setvec, lincom2)
round(m),round(n) 

(6.0, 3.0)

### Some special properties of the standard basis vectors

1. It is orthogonal, i.e. the vectors (1,0) and (0,1) are perpendicular to each other.
2. It is normalized, i,e. the magnitude of each vectors is 1.

Or you can say that it is orthonormal.
Let's verify this and check some other orthonormal basis vectors

In [7]:
## First we'll see whether they're perpendicular or not. 
##We'll use the concept of dot products here.
## Dot products of perpendicular vectors are always zero
setvec = np.array([[1,0],[0,1]])
np.dot(setvec[0],setvec[1])

0

In [8]:
#Now let's check whether they're normalized or not.
##This would mean that each of them would be of unit magnitude
np.linalg.norm(setvec[0])

1.0

In [9]:
np.linalg.norm(setvec[1])

1.0

### Linear Transformations

A linear transformation is essentially a matrix transformation on a vector where the vector's geometric properties gets changed  due to elongation, rotation, shifting of axes or some other form of distortion.
If L is matrix that denotes the transformation and v is the vector on which the transformation is happening, then the resultant vector is given by Lv. 


Let's go through the following examples to understand how a linear transformation happens and what changes it makes to the dataset.

####  Elongation 

First we'll see how multiplying a vector/matrix with another vector elongates it.Let's consider a linear transformation where the original basis vectors i(1,0) and j(0,1) move to the points i'(2,0) and j'(0,1)

In [10]:
#Let's create a dataframe matrix here to understand the effect.
a = [[1,2],[-2,3],[-2,1],[3,7],[4,5],[6,4]]
b = ['X','Y']
c = pd.DataFrame(a,columns = b)
c

X  Y
0  1  2
1 -2  3
2 -2  1
3  3  7
4  4  5
5  6  4

In [12]:
## Now let's denote the linear transformation matrix.
## (2,0) and (0,1) are the vectors that would denote the columns of this matrix.
## Therefore (2,0) and (0,1) would be the rows
L = np.array([[2,0],[0,1]])
L

array([[2, 0],
       [0, 1]])

In [13]:
#Let's apply the transformation now.
#Note that we have used c.values to convert that dataframe to a numpy array 
#And taken its transpose so that the transformation happens on each vector
d  = L @ (c.values).T

In [14]:
#Now let's show the final changed matrix by findings the transpose again.
d.T

array([[ 2,  2],
       [-4,  3],
       [-4,  1],
       [ 6,  7],
       [ 8,  5],
       [12,  4]], dtype=int64)

#### Shifting of axes

Let's say from the original basis vectors i(1,0) and j(0,1) we want to shift it to the new orthonormal basis vectors i'(0.8,0.6) and j'(-0.6,0.8). 

In [15]:
L = np.array([[0.8,-0.6],[0.6,0.8]])

In [16]:
d  = L @ (c.values).T
d.T

array([[-0.4,  2.2],
       [-3.4,  1.2],
       [-2.2, -0.4],
       [-1.8,  7.4],
       [ 0.2,  6.4],
       [ 2.4,  6.8]])

This is also known as BASIS TRANSFORMATION where you shift the original standard basis to a new basis

### Eigenvectors and Eigendecomposition

A special kind of linear transformation that can happen to a vector is that when a matrix is multiplied to it, it only manages to stretch the vector by a certain scalar magnitude. These vectors are known as eigenvectors for that particular matrix and that scalar magnitude is known as the corresponding eigenvalue. Formally, they can be written as follows,

Av = λv , where A is the original matrix / linear transformation, v is the eigenvector and λ is the corresponding eigenvalue.

Let's go through a few demonstrations to understand how they can be derived. Observe that here we are going the reverse route. Instead of finding the effect the linear transformation matrix has on the vector, in this case, we have the matrix and the effect it generates. We need to find all the vectors where this effect is visible.

In [17]:
#Let's take the following matrix as an example
A = np.array([[2,1],[1,2]])
A

array([[2, 1],
       [1, 2]])

In [18]:
#Let's find the eigenvectors of A. Note that both the eigenvectors and eigenvalues are different.
K = np.linalg.eig(A)
K

(array([3., 1.]), array([[ 0.70710678, -0.70710678],
        [ 0.70710678,  0.70710678]]))

In [19]:
#Eigenvalues
K[0]

array([3., 1.])

In [20]:
#Eigenvectors
K[1]

array([[ 0.70710678, -0.70710678],
       [ 0.70710678,  0.70710678]])

In [23]:
#let's verify them once again. First let's calculate Av
A @ (K[1].T)[0]

array([2.12132034, 2.12132034])

In [24]:
#Now let's calculate λv.
3*(K[1].T)[0]

array([2.12132034, 2.12132034])

As you can see Av = λv has been verified.

#### Let's use the results we've obtained till now to do a neat little matrix manipulation that leads to a very important observation.

In [25]:
np.diag(K[0])

array([[3., 0.],
       [0., 1.]])

In [26]:
#First let's arrange the eigenvalues along the diagonal of a square matrix.
S = np.array([[3,0], [0,1]])
S

array([[3, 0],
       [0, 1]])

In [27]:
Q=K[1]
Q

array([[ 0.70710678, -0.70710678],
       [ 0.70710678,  0.70710678]])

In [28]:
P = np.linalg.inv(Q)
P

array([[ 0.70710678,  0.70710678],
       [-0.70710678,  0.70710678]])

In [29]:
#Let's compute the product of the three matrices obtained in the following order.
Q @ S @ P

array([[2., 1.],
       [1., 2.]])

## We've obtained the original matrix that we started with!

This trick that we just did is called the eigendecomposition of a matrix, which states that as long as A is a square diagonalizable matrix, it can always be decomposed into 3 matrices Q, S and P, where

1. Q is the eigenvector matrix
2. S is a diagonal matrix with the eigenvalues as the diagonal elements
3. P is the inverse of the matrix Q.

In [34]:
a = np.array([[1,2,3],[4,5,6],[1,2,6]])
sol = ([19,29,54])

x1,x2,x3 = np.linalg.solve(a, sol)

print(round(x1), round(x2), round(x3))

-1.0 -8.0 12.0


In [35]:
setvec = np.array([[1,0],[0,1]])
np.dot(setvec[0],setvec[1])

0

In [40]:
c = np.array([[-1,-2],[2,-1]])
c = np.array([[-1,2],[-2,-1]])
print(np.dot(c[0],c[1]))
print(np.linalg.norm(c[0]), np.linalg.norm(c[1]))

0
2.23606797749979 2.23606797749979


In [41]:
d = np.array([[1,4],[4,2]])
d

array([[1, 4],
       [4, 2]])

In [43]:
x = np.array([[1,2],[3,4],[5,6],[7,8]])
x

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [45]:
(d @ x.T).T

array([[ 9,  8],
       [19, 20],
       [29, 32],
       [39, 44]])