#### Principal Component Analysis

The properties of PCA as mentioned in the video are as follows:
1. They're weighted linear combinations of the original variables.
2. They're perpendicular to each other. 
3. They capture maximum variance of the data and are ordered.

Let's go ahead and verify these properties

In [1]:
import pandas as pd 
import numpy as np

In [2]:
#Let's now take the following dataframe
a = [[0,0,0],[1,2,3],[2,4,5],[3,6,2],[4,8,3],[5,10,1]]
b = ['X','Y','Z']
dat = pd.DataFrame(a,columns = b)
dat

X   Y  Z
0  0   0  0
1  1   2  3
2  2   4  5
3  3   6  2
4  4   8  3
5  5  10  1

In [3]:
#Importing the PCA module
from sklearn.decomposition import PCA
pca = PCA(svd_solver='randomized', random_state=42)

In [4]:
#Applying PCA on the dataset
pca.fit(dat)

PCA(copy=True, iterated_power='auto', n_components=None, random_state=42,
  svd_solver='randomized', tol=0.0, whiten=False)

In [5]:
#Let's check the components
pca.components_

array([[-4.46999485e-01, -8.93998971e-01, -3.09402653e-02],
       [-1.38369073e-02, -2.76738146e-02,  9.99521235e-01],
       [ 8.94427191e-01, -4.47213595e-01,  9.16794248e-19]])

### Property 1: Principal Components are weighted linear combinations of Original Variables

In [6]:
pca.components_[0]

array([-0.44699949, -0.89399897, -0.03094027])

In [7]:
#The original variables are the original axes here given by X(1,0,0), Y(0,1,0) and Z(0,0,1)
#We need to show that PCs that are formed are the linear combinations of X,Y and Z.
lincom  = pca.components_[0]
setvec = np.array([[1,0,0],[0,1,0],[0,0,1]])
x,y,z = np.linalg.solve(setvec, lincom)
round(x,2),round(y,2),round(z,2)


(-0.45, -0.89, -0.03)

Hence it is verfied that these PCs are linear combinations of the original variables

### Property 2: Principal Components are perpendicular to each other

In [8]:
#For verifying this we would be calculating the dot product of any of the two PCs.
#We know that dot product of any 2 perpendicular vectors is 0.
round(np.dot(pca.components_[0],pca.components_[1]))

0.0

### Property 3: Principal Components capture maximum variance and are ordered.

In [9]:
#First let us see what is the variance given by the PCs
pca.explained_variance_ratio_

array([8.51564515e-01, 1.48435485e-01, 2.52357338e-66])

In [10]:
pca.explained_variance_ratio_.round(2)

array([0.85, 0.15, 0.  ])

#### Let's verify this calculation by projecting the data onto the principal components

In [11]:
#We can directly use the pca function pca.fit_transform
#This is equivalent to the basis transformation that we did earlier.
#To project the data
dat_new2 = pca.fit_transform(dat)
cols = ['X','Y','Z']
dat_new3 = pd.DataFrame(dat_new2, columns = cols).round(2)
dat_new3

X     Y    Z
0  5.66 -2.16  0.0
1  3.33  0.77 -0.0
2  1.03  2.70  0.0
3 -1.11 -0.37  0.0
4 -3.37  0.56  0.0
5 -5.55 -1.51  0.0

In [12]:
100*np.var(dat_new3)/sum(np.var(dat_new3))

X    85.145166
Y    14.854834
Z     0.000000
dtype: float64

Hence it has been verified.

In [13]:
#let's do one final calculation
sum(np.var(dat))

17.138888888888886

In [14]:
sum(np.var(dat_new3))

17.14266111111111

#### This is what PCA does. It doesn't change the total variance of the dataset. It only rearranges them in the direction of maximum variances