In [1]:
import numpy as np
import pandas as pd

In [18]:
sample_arr = np.arange(1, (11*12)+1)

In [19]:
print(sample_arr, len(sample_arr), (11*12))

[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107 108
 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125 126
 127 128 129 130 131 132] 132 132


In [20]:
sample_arr = np.reshape(sample_arr, (11,12))

In [21]:
sample_arr

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12],
       [ 13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24],
       [ 25,  26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36],
       [ 37,  38,  39,  40,  41,  42,  43,  44,  45,  46,  47,  48],
       [ 49,  50,  51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70,  71,  72],
       [ 73,  74,  75,  76,  77,  78,  79,  80,  81,  82,  83,  84],
       [ 85,  86,  87,  88,  89,  90,  91,  92,  93,  94,  95,  96],
       [ 97,  98,  99, 100, 101, 102, 103, 104, 105, 106, 107, 108],
       [109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120],
       [121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132]])

In [13]:
np.where(sample_arr==100, [i,j])

print(i,j)

NameError: name 'i' is not defined

In [26]:
print(np.unravel_index(100,(11,12)))

(8, 4)


In [28]:
sample_arr[8,4]

101

In [32]:
sample_arr[:,:3]

array([[  1,   2,   3],
       [ 13,  14,  15],
       [ 25,  26,  27],
       [ 37,  38,  39],
       [ 49,  50,  51],
       [ 61,  62,  63],
       [ 73,  74,  75],
       [ 85,  86,  87],
       [ 97,  98,  99],
       [109, 110, 111],
       [121, 122, 123]])

In [35]:
import numpy as np 

# Given array
a = np.array([[4, 3, 1], [5, 7, 0], [9, 9, 3], [8, 2, 4]])

# Read the values of m and n
import sys
lines = sys.stdin.readlines()
m = int(input())
n = int(input())

print('before swap')
print(a)

print('after swap')
# Write your code for swapping here
a[[m,n]] = a[[n,m]]
# Print the array after swapping
print(a)

0
2
before swap
[[4 3 1]
 [5 7 0]
 [9 9 3]
 [8 2 4]]
after swap
[[9 9 3]
 [5 7 0]
 [4 3 1]
 [8 2 4]]


In [12]:
# Read the variable from STDIN
# n = 4 #int(input())

import numpy as np
n = int(input())
a = np.zeros((n,n), dtype=int)
print(a)
a[0, :] = 1
a[-1, :] = 1
a[:, 0] = 1
a[:, -1] = 1

print(a)

6
[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]
[[1 1 1 1 1 1]
 [1 0 0 0 0 1]
 [1 0 0 0 0 1]
 [1 0 0 0 0 1]
 [1 0 0 0 0 1]
 [1 1 1 1 1 1]]


In [13]:
Z = np.tile( np.array([[0,1],[1,0]]), (4,4))
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [18]:
n = int(input())
print(np.tile(([[0,1],[1,0]]), (n//2,n//2)))

8
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
